name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: quizwiz
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set FLASK_ENV to testing
        run: echo "FLASK_ENV=testing" >> $GITHUB_ENV

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/QuizWiz_Backend" >> $GITHUB_ENV

      - name: Initialize database
        run: |
          python -c "
          from QuizWiz_Backend.app import db, create_app
          with create_app().app_context():
            db.create_all()  # Si ya tienes la base de datos configurada, solo debería crear las tablas
          "
      - name: Set DATABASE_URL for PostgreSQL
        run: echo "DATABASE_URL=postgresql://postgres:root@localhost:5433/quizwiz" >> $GITHUB_ENV
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:root@localhost:5433/quizwiz
        run: pytest
